# Site Settings
title: "Pilo'Press"
email: dev@pilot-in.com
author: "Pilot'in"
description: "Awesome framework for WordPress"
baseurl: "/PiloPress"
url: "https://pilot-in.github.io"
remote_theme: pmarsceill/just-the-docs

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
